[project]
name = "checkout"
version = "0.1.0"
description = "Eats hackathon project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "playwright>=1.49.1",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.37",
    "typer>=0.15.1",
    "psycopg2>=2.9.10",
]

[project.scripts]
checkout = "checkout:main"

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

